(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.webFontTxtInst = {}; 
var loadedTypekitCount = 0;
var loadedGoogleCount = 0;
var gFontsUpdateCacheList = [];
var tFontsUpdateCacheList = [];
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[0,0,300,600],[302,0,159,219],[0,602,110,110],[112,602,107,105],[302,221,112,203],[302,426,156,142],[302,570,167,108]]}
];



lib.updateListCache = function (cacheList) {		
	for(var i = 0; i < cacheList.length; i++) {		
		if(cacheList[i].cacheCanvas)		
			cacheList[i].updateCache();		
	}		
};		

lib.addElementsToCache = function (textInst, cacheList) {		
	var cur = textInst;		
	while(cur != null && cur != exportRoot) {		
		if(cacheList.indexOf(cur) != -1)		
			break;		
		cur = cur.parent;		
	}		
	if(cur != exportRoot) {		
		var cur2 = textInst;		
		var index = cacheList.indexOf(cur);		
		while(cur2 != null && cur2 != cur) {		
			cacheList.splice(index, 0, cur2);		
			cur2 = cur2.parent;		
			index++;		
		}		
	}		
	else {		
		cur = textInst;		
		while(cur != null && cur != exportRoot) {		
			cacheList.push(cur);		
			cur = cur.parent;		
		}		
	}		
};		

lib.gfontAvailable = function(family, totalGoogleCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], gFontsUpdateCacheList);		

	loadedGoogleCount++;		
	if(loadedGoogleCount == totalGoogleCount) {		
		lib.updateListCache(gFontsUpdateCacheList);		
	}		
};		

lib.tfontAvailable = function(family, totalTypekitCount) {		
	lib.properties.webfonts[family] = true;		
	var txtInst = lib.webFontTxtInst && lib.webFontTxtInst[family] || [];		
	for(var f = 0; f < txtInst.length; ++f)		
		lib.addElementsToCache(txtInst[f], tFontsUpdateCacheList);		

	loadedTypekitCount++;		
	if(loadedTypekitCount == totalTypekitCount) {		
		lib.updateListCache(tFontsUpdateCacheList);		
	}		
};
// symbols:



(lib.halfpagebannerholidaymainstable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.halfpageholidaymainspotatoes = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.halfpageholidaymainsstuffing = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.holidaymainsapple = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.holidaymainsbrusselsprouts = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.holidaymainscinnamonbuns = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.holidaymainscranberries = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.youtakethecredit = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgIAJQgFgDAAgGQAAgFAFgDQADgEAFgBQAGABAEAEQADADAAAFQAAAGgDADQgEAEgGAAQgFAAgDgEg");
	this.shape.setTransform(114.4,5.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAAAAAQABgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_1.setTransform(105.8,-0.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgEBHQgGAAgCgEIAAiFQABgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAIAEgCIAFAAIAFAAQAFABACAEIAACEQgBABAAAAQAAABgBAAQAAABAAAAQgBAAAAABIgFABIgFABg");
	this.shape_2.setTransform(97,-0.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("Ag6BFIgFgBQgCgCAAgDIAAh9QAAAAAAgBQAAgBAAAAQABgBAAAAQAAgBABAAQACgCADAAIAzAAIAOABIAOAEQANAFAKAJQAKAJAGANQADAGACAHQABAHAAAHQAAAQgGAMIgHAMIgJALIgLAHIgNAGQgNAFgOAAgAglgqQgDACAAAEIAABLQAAADADACIAFABIAZAAQAJAAAJgDQAIgDAHgGQAHgGAEgIQAEgJAAgKQAAgJgEgIQgEgJgHgGQgHgFgIgEQgJgDgJAAIgZAAQgDAAgCACg");
	this.shape_3.setTransform(86.6,-0.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgvBFIgDgCQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAEgBIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIACADIAAAGIAAADIgBAGIgEADIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAASQAAADACACQACABADAAIAtAAQABAAABABQAAAAABAAQAAAAAAABQAAAAABABIABAEIABAGIAAADQAAAFgGACIgtAAQgCABgCACQgBABAAAAQgBABAAAAQAAABAAAAQgBABAAABIAAAUQAAADACADQACABADAAIBGAAQAFADAAAFIAAAEIAAAGIgCAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_4.setTransform(72.1,-0.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAjBGIgEgBIgCgBIgCgCIgYgkIgDgFQgDgCgEAAIgRAAQgDAAgCADQgCABAAADIAAAiQAAABAAAAQAAABAAABQgBAAAAAAQgBABAAAAIgFACIgFAAIgFAAQgEAAgCgCQgCgBAAgFIAAh+QAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAAAABAAQAAgBAAAAQABAAABAAQAAAAABAAIA6AAQAKAAAJADQAKADAGAGQAHAGADAJQAEAJAAALQAAALgEAIQgFAGgFAEIgKAIQgEADAAADIAAADIAGAHIAIAMIAHALQADAFAAACQAAAAAAABQAAABgBAAQAAABAAAAQAAAAgBABIgEADIgFACIgFAAgAgcgsQgDACAAAEIAAAfQAAAEADACQADABADAAIAcAAQAFAAAFgBQAFgBADgDQAEgDACgEQACgFAAgFQAAgMgIgGQgDgCgFgCQgFgBgFAAIgcAAIgGABg");
	this.shape_5.setTransform(58.2,-0.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgFBHIgOgEIgNgHIgLgIIgJgLIgHgMQgGgNAAgQQAAgOAGgOIAHgMQAEgGAFgEQAKgKAOgGIAOgEQAGgBAHAAQAIAAAIACQAIABAIAEQAHADAHAFQAGAEAFAHIABADQAAAEgDACIgFAEIgEACQgDACgCAAQgDAAgDgDIgHgGQgEgEgHgDQgHgDgKAAQgIAAgJAEQgIAEgHAHQgGAGgEAJQgEAJAAAIQAAAKAEAJQAEAIAGAHQAHAGAIAEQAJAEAIAAQALAAAJgEQAKgEAHgIIAEgBIAFABIAFADIAFAEQAAABABAAQAAABAAABQABAAAAABQAAAAAAABIgBADIgMALIgNAIIgQAFQgHABgJAAQgHAAgGgBg");
	this.shape_6.setTransform(43.1,-0.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgvBFIgDgCQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQAAAAABgBIAEgBIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAAAABIACADIAAAGIAAADIgBAGIgEADIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQgBABAAABQAAAAAAABQgBAAAAABIAAASQAAADACACQACABADAAIAtAAQABAAABABQAAAAABAAQAAAAAAABQAAAAABABIABAEIABAGIAAADQAAAFgGACIgtAAQgCABgCACQgBABAAAAQgBABAAAAQAAABAAAAQgBABAAABIAAAUQAAADACADQACABADAAIBGAAQAFADAAAFIAAAEIAAAGIgCAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_7.setTransform(24,-0.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AAlBGQgDgBgCgCIAAgxQAAgDgDgDQgCgCgDAAIguAAQgDAAgDADQgCADAAADIAAAvQAAABAAAAQgBABAAABQAAAAgBAAQAAABgBAAIgFABIgFAAIgFAAIgFgBQAAgBgBAAQAAAAgBgBQAAAAgBgBQAAAAAAgBIAAiDIADgDIAFgCIAFAAIAEAAQAGAAADAFIAAAtIABAFQACACADAAIAwAAQADAAACgCQADgCAAgEIAAgsQACgEAEAAIAJgBIAGABIAEAEIAACDQgCAEgEABIgJAAg");
	this.shape_8.setTransform(9.2,-0.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAABAAQAAgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_9.setTransform(-4.2,-0.4);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AguBFIgFgCQAAAAgBAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIAAh/QAAgBAAAAQAAgBAAAAQABgBAAAAQABAAAAgBIAEgBIBgAAQABAAAAAAQABABAAAAQABAAAAABQAAAAABABIABADIAAAGIAAADIgBAGIgEADIhHAAQAAAAgBAAQAAAAgBABQAAAAgBAAQAAABAAAAQgBABAAAAQgBABAAABQAAAAAAABQAAAAAAABIAAASQAAADABACQACABADAAIAuAAQAAAAABABQAAAAABAAQAAAAAAABQAAAAABABIABAEIAAAGIAAADQAAAFgEACIguAAQgCABgCACQgBABAAAAQgBABAAAAQAAABAAAAQAAABAAABIAAAUQAAADABADQACABADAAIBGAAQAEADABAFIAAAEIAAAGIgCAEQAAABgBAAQAAAAAAABQgBAAAAAAQgBAAgBAAg");
	this.shape_10.setTransform(-21.7,-0.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AAgBHQgEgBgBgCIgig0QgCgCgDgBIgGgCQgDAAgDACQgFACAAAEIAAArQAAADgCACIgFACIgFABIgFAAQgIAAAAgHIAAiBIAEgDIADgCIAFAAIAEAAQAHAAACAFIAAArQAAADAEACQACACADAAQADAAADgDIAmgvIADgBIADgBIAEABIAGADIAEAEQAAAAABABQAAAAAAAAQAAABAAAAQABABAAAAIgCADIghAoIgCADIgBAEIABADIABADIAsA8IABACIAAACQAAAAgBABQAAAAAAABQAAAAgBABQAAAAgBABIgEADIgGACIgEAAg");
	this.shape_11.setTransform(-35.1,-0.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#006E47").s().p("AAyBGIgHgBQgEgBgBgDIgIgTIgCgDIgEgCIguAAIgCABIgCABIgCACIgBABIgIATIgCACIgEABIgEABIgEAAIgEAAIgEAAIgEgCQAAAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAAAIA4iCQAAgBABAAQAAgBABAAQAAAAABgBQAAAAABAAIAEgBIAGABQAEAAABADIA2CBIAAABQAAABAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgEABIgFABgAgBgVIgBABIgCAFIgDAGIgDAIIgDAGIgDAHIgBADIABADIADABIAbAAIADgBIABgDIgCgFIgFgLIgEgMIgDgHQgBAAAAgBQAAAAgBAAQAAAAgBAAQAAAAgBgBg");
	this.shape_12.setTransform(-49.2,-0.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#006E47").s().p("AgCBFIgGgBQgEgBAAgEIAAhmQAAgBAAAAQAAgBAAgBQgBAAAAgBQAAAAgBgBQgBgBgFAAIgLAAIgKAAIgGAAQgEAAgBgDQgCgDAAgEIAAgEIABgFIACgDQAAgBABAAQAAAAAAAAQABgBABAAQAAAAABAAIBfAAQAEAAABADIACAGIAAAEIgBAFIgCAEQgBABAAAAQAAAAgBAAQAAABgBAAQgBAAAAAAIgcAAQgDAAgCABQgDACAAAEIABBkQAAAEgCABIgEACIgFABg");
	this.shape_13.setTransform(-61.6,-0.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#006E47").s().p("AgXBDQgLgEgIgIQgIgIgFgKQgDgGgBgGIgBgMIAAgmIAAgmQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAABgBIAEgCIAGgBIAEAAIAGACQADABAAADIAABHQAAAIADAIQACAHAFAFQAEAGAHADQAHAEAHAAQAJAAAGgEQAHgDAFgFQAEgGADgHQACgIAAgIIAAhGQAAgEADgCQADgBADAAIAFgBIAGABIAEACQABACAAADIAABMIgBAMIgEAMQgEAKgJAIQgIAIgLAEQgLAFgNAAQgMAAgLgFg");
	this.shape_14.setTransform(-80.9,-0.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#006E47").s().p("AgOBHIgOgFIgNgGIgKgJQgLgKgFgNQgDgHgCgGIgBgPIABgOQACgHADgGQAFgOALgJIAKgJQAGgEAHgCQAGgEAIgBQAHgBAHAAIAPABQAHABAHAEQAOAFAJAKQALAJAFAOQAGANAAAOQAAAHgBAIIgFANQgFANgLAKQgJAKgOAFIgOAFIgPABQgHAAgHgBgAgRgrQgJADgGAHQgGAHgEAIQgFAJAAAJQAAAKAFAJQAEAJAGAGQAGAGAJAEQAJAEAIgBQAJABAJgEQAJgEAGgGQAGgGAEgJQAEgJAAgKQAAgJgEgJQgEgIgGgHQgHgHgIgDQgJgEgJAAQgIAAgJAEg");
	this.shape_15.setTransform(-96.7,-0.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#006E47").s().p("AgFBIIgDgBIgCgCIgBgCIAAgyIgCgHIgEgHIgng9IAAgBQAAgBAAgBQAAAAAAgBQAAAAABgBQAAAAABgBIADgDIAGgDIAEgBIAFABIADADIAbAtIADACIADABIADgBIADgBIAcguQAAgBAAAAQAAAAABgBQAAAAABAAQAAgBABAAIAFgCIAEABIAGADIADADQABAAAAABQABABAAAAQAAABAAAAQAAABAAAAIAAACIgBABIgnA9IgEAJIgBADIAAACIAAAyQgCAFgEAAIgHAAg");
	this.shape_16.setTransform(-111.2,-0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.youtakethecredit, new cjs.Rectangle(-119.5,-12.1,239,24.3), null);


(lib.wellmakeuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AhKBWQghghABgxQgBg1AigjQAhgjA0AAQAsABAaAZQAZAZAAArQAAAOgEAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAIAAIAvAAIALgCQAEgBAAgGQgBgWgPgPQgPgPgUAAQgbAAgNAYQgNAXgBAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAGAAQAFAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgvAAghgig");
	this.shape.setTransform(104.4,5.3);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("ABKCnIgJgBQgKgEgWgcIgKgMIgDgFQg4hIgEAAQgBAAAAAAQgBAAAAABQgBAAAAAAQgBABAAABIgBAJIAAAKIACAwQABAOADADIANAHQALAFAAAIQAAAJgLAEQgMADgeAAQgjAAgLgDQgLgFAAgKQAAgHALgEIAGgCQAGgEADgLQACgMAAgaIAAgcIAAgkIAAgbIgBhWQgCgUgDgFQgDgCgKgDIgIgDIgIgEIgCgGQAAgGAEgEQAFgEAQgFIAfgJIAXgDQAHAAADAEQADAFAAAKIgBAtIgCA7IAAA5IABALQAAABABAAQAAABABAAQAAAAABAAQAAAAABAAIAJgFIARgOIAWgVQAGgHAAgDQAAgCgJgFQgIgEAAgHQAAgLAMgEQALgDAhAAQAVAAALADQAKAEAAAKQAAAKgRAEQgQAFgIAEQgHAEgUAUIgEADIgIAIIgCAFQAAAFAUAaIADADIAnAwQAQATAJAHQAGAEAOAEQAPAEAAAJQAAALgKAEQgLAEgZAAg");
	this.shape_1.setTransform(80.4,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AApBsIgMgMIgKAFQgcATgcAAQgiAAgVgUQgUgTAAggQAAgkAagUQAbgVAwAAQALAAAGAEQAFADAAAJQAAANgPAAQgWAAgOALQgOALAAATQAAASAMALQAMALAUAAQAVAAAKgKQAKgKAAgYIAAhWQAAgUgJgLQgJgLgPAAQgMAAgJAFQgKAFgJAKIgFAGQgOASgPAAQgJAAgFgGQgGgGAAgKQAAgVAbgPQAagPAqAAQAZAAASAHQASAHAKANQAHAIADAOQADAPAAAgIAABJQAAANACAGQACAHAFABIAHACQAOAEAAAIQAAALgPAJQgQAJgUAAQgKAAgLgMg");
	this.shape_2.setTransform(54.8,5.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABVChQgMgEAAgKQAAgJAOgFIAKgFQAEgDACgLQABgKAAgeIAAgMIAAhhIgBg6IgdBMQhDCugPAAQgHAAgNgXQgNgYgghLIgyhyIgCBaIgBA9IABArQACAKADADIAKAFQAPAEAAAKQAAAKgMAEQgMAEgcAAQgZAAgLgEQgLgEAAgLQAAgHAMgGQAMgGACgFQADgKADg7QAEg7AAhIIAAgHQAAgYgCgIQgCgIgFgEIgLgEQgPgGAAgJQAAgJAKgDQALgEAhAAIAgABIAKACQAEADAQApIANAgIAHAQQA3CJAEAAQAFAAAVgxQAUgwAchRIAFgOQAIgZAHgIQAEgEAJgBIAfgCQAfAAAKAEQAKADAAAJQAAAJgNAFIgGACQgHAFgCAJQgDAIAAAjIADCDQACA6ACAIQACAGAKADIAFADIAJAFQACADAAAFQAAAKgNAEQgMAEgmAAQgiAAgNgEg");
	this.shape_3.setTransform(21.6,0.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgmClQgLgFAAgKQAAgGAJgFIAMgGQAEgDABgPIACgtIAAgkIgBgqIAAgRQAAg6gBgRQgCgQgFgDIgOgFQgPgEAAgIQAAgGAFgEQAFgEAPgFIAggJIAWgDQAHAAADAEQADAFAAAKIgBASQgCBRgBBSIACBPQABAQAEAEIANAHQALAFAAAIQAAAJgMAEQgLADgeAAQgiAAgLgDg");
	this.shape_4.setTransform(-18.5,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgmClQgLgFAAgKQAAgGAJgFIAMgGQAEgDABgPIACgtIAAgkIgBgqIAAgRQABg6gCgRQgCgQgFgDIgOgFQgPgEAAgIQABgGAEgEQAEgEARgFIAegJIAXgDQAHAAADAEQACAFAAAKIAAASQgCBRgBBSIACBPQACAQADAEIANAHQAKAFAAAIQAAAJgLAEQgLADgeAAQgiAAgLgDg");
	this.shape_5.setTransform(-31.3,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgDBDIgQhlIgBgDIAAgFQAAgLAGgHQAFgFAJAAQAKAAAGAFQAFAHAAALIAAAFIAAAEIgRBkg");
	this.shape_6.setTransform(-41.3,-8.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhKBWQghghAAgxQAAg1AigjQAhgjA0AAQAsABAaAZQAZAZAAArQAAAOgDAFQgFAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAIAAIAvAAIALgCQAEgBAAgGQAAgWgQgPQgPgPgUAAQgbAAgOAYQgNAXAAAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAHAAQAEAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgwAAgggig");
	this.shape_7.setTransform(-57.2,5.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AAfBQIgwh/QgPgpgJgTQgKgTgIgHIgNgFQgLgEAAgJQAAgJALgEQAKgDAsAAQAqAAALADQAKAEAAAJQAAAJgRAGIgCABQgFACgDADQgDAEAAAFQAAAIALAfIAmBkIAQAkQAFAKAEAAQADAAAFgIIAPghIAEgKQAvhxAAgOQAAgHgDgFQgEgFgHgDIgGgDQgNgFAAgJQAAgJAJgEQAJgDAmAAQAkAAAJADQAKAEAAAJQAAAJgOAFIgJAFQgQALgeBOIgTAvIgsBsIgIAUQgOAkgKAAQgMAAgihYgAheCVIgDgHQgdhAgth1IgVg2IgOgcQgFgJgIgFIgGgCQgPgFAAgJQAAgJALgEQALgDArAAQArAAALADQAKAEAAAJQAAAJgRAHIgCAAQgGACgCADQgDAEAAAFQAAAHAKAcIAmBkIASAqQAEAIAEAAQAEAAAFgLIALgaQAFgQANAAQAOAAAAAQIgDAOIgeBJIgGARQgPAlgJAAQgIAAgIgTg");
	this.shape_8.setTransform(-92.9,0.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.wellmakeuse, new cjs.Rectangle(-118.5,-29.1,237.1,58.4), null);


(lib.theturkeyuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgZAZQgJgKgBgPQABgOAJgKQALgLAOAAQAPAAAKALQALAKgBAOQABAPgLAKQgLALgOAAQgOAAgLgLg");
	this.shape.setTransform(113.7,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhpCXQgLgKAAgOQAAgLAIgJQAIgHALAAIAKABIAHAFIAHAIQAGAKAEgBQAMAAAMgQQAMgRAAgSQAAgUgQgkIgDgFIgkhPIgVgtQgEgJgOgFIAAgBQgIgCgDgDQgCgEAAgEQAAgLAMgEQAMgDAhAAQAigBALAEQALADAAAKIgBAHIgFAFIgIADQgJAEAAADIAFASIASAtIASAsQAGALAEgBQACABAFgLIAPgkIARguQAFgQAAgGQAAgHgMgGQgNgIAAgGQAAgIAKgDQAKgEAaABQAcgBAKAEQAJADAAAKQAAAIgNAEIgJADQgNAHgPAmIgGASIgeBJQglBggYAcQgYAcghAAQgRAAgLgJg");
	this.shape_1.setTransform(96.1,9.9);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhKBWQggghgBgxQABg1AhgjQAigjAyAAQAtABAaAZQAZAZABArQAAAOgFAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAHAAIAwAAIAMgCQACgBAAgGQABgWgPgPQgQgPgUAAQgbAAgOAYQgMAXAAAiQgBAjATAaQASAaAcAAQARAAAMgDQALgFAMgHIAIgGQALgKAGAAQAGAAADADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgVABQgwAAghgig");
	this.shape_2.setTransform(72.4,5.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("ABKCnIgJgBQgKgEgWgcIgKgMIgDgFQg4hIgEAAQgBAAAAAAQgBAAAAABQgBAAAAAAQAAABgBABIgBAJIAAAKIACAwQABAOADADIANAHQALAFAAAIQAAAJgLAEQgMADgeAAQgjAAgLgDQgLgFAAgKQAAgHALgEIAGgCQAGgEADgLQACgMAAgaIAAgcIAAgkIAAgbIgBhWQgCgUgDgFQgDgCgKgDIgIgDIgIgEIgCgGQAAgGAEgEQAFgEAQgFIAfgJIAXgDQAHAAADAEQADAFAAAKIgBAtIgCA7IAAA5IABALQABABAAAAQAAABABAAQAAAAABAAQAAAAABAAIAJgFIARgOIAWgVQAGgHAAgDQAAgCgJgFQgIgEAAgHQAAgLAMgEQALgDAhAAQAVAAALADQAKAEAAAKQAAAKgRAEQgQAFgIAEQgHAEgUAUIgEADIgIAIIgCAFQAAAFAUAaIADADIAnAwQAQATAJAHQAGAEAOAEQAPAEAAAJQAAALgKAEQgLAEgZAAg");
	this.shape_3.setTransform(48.4,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhEByQgMgEAAgKQAAgIALgEIAGgCQAGgEACgHQADgIAAgRIAAgQIAAgSIAAgOQAAgpgCgNQgCgNgFgCIgLgEQgNgFAAgHQAAgGAEgEQAEgEAKgEIAfgKIAVgEQAKAAAEAfIABAFIABABQALgTANgJQANgKANAAQAQAAAKAKQAJAJAAAQQAAAQgHAJQgIAJgNAAIgLgCIgJgHIgGgJQgCgGgDAAQgQAAgGAWQgFAWAABFQAAAUACAKQACAKAHADIAJADQAOAEgBAJQABAJgNAEQgNADgfAAQgiAAgLgDg");
	this.shape_4.setTransform(26.6,5.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AAxB0QgDgDAAgIIAAgQIAAgBIgBgBQgCAAgGAGIgDADQgLAMgOAFQgMAGgSAAQgRAAgPgHQgPgGgKgMQgLgNgFgTQgEgSAAgwIABgQIAAgRIAAgEQgBgTgCgFQgCgFgJgDIgJgDQgNgEAAgIQAAgGAEgDQAFgEAQgGIAfgIIAZgEQAFAAAEAFQACAFAAAKIAAAJIgCBVQgBAuAKASQAKASAXAAQAZAAAMgXQALgXAAg3IAAgSQAAgSgCgFQgDgGgHgCIgKgDQgNgEAAgIQABgFAEgEQAFgEAPgGIAfgIIAYgEQAHAAACAFQADAEAAALIAAANIgDBdIAAAnIACAPQACAJAMAFIAEABQANAFAAAHQAAAFgEAEQgFAEgJAEIghALQgQAEgIAAQgGAAgEgEg");
	this.shape_5.setTransform(3.5,5.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgwCiQgMgDAAgKQAAgKAMgEQAMgFADgEQACgDABgmIAChrIgBg9IgCgkQAAgHgFgBQgDgCgKAAIgKAAQgPgBgKAEQgIAEgHAJIgHAPIgGAQIgHAHQgEACgFAAQgGABgDgHQgDgFAAgPQAAgdAHgTQAHgSALAAIADAAQARACAcAAICGAAQAbAAATgCIACAAQAMAAAHASQAHATAAAdQAAAOgDAGQgEAHgGgBIgIgCIgHgHIgHgQIgHgPQgGgJgJgEQgJgEgQABIgJAAQgKAAgEACQgEABAAAHIgCAlIgBA8IABBrQABAmADADQACAEANAFQAMAEAAAKQAAAKgNADQgNAFgjAAQgjAAgNgFg");
	this.shape_6.setTransform(-24.8,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhKBWQghghAAgxQAAg1AigjQAhgjA0AAQAsABAaAZQAZAZAAArQAAAOgDAFQgFAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAIAAIAvAAIALgCQAEgBAAgGQAAgWgQgPQgPgPgUAAQgbAAgOAYQgNAXAAAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAHAAQAEAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgwAAgggig");
	this.shape_7.setTransform(-64.4,5.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AAgCkQgLgDAAgJQAAgJALgEIAJgEQAFgDACgKQACgJAAgZQAAhJgJgSQgJgSgZAAQgLAAgLAHQgLAHgGAMQgFAKgCARQgCASAAAtQAAAXACAHQACAIAFACIAIAEQAMAEAAAJQAAAJgLADQgLAEgeAAQgkAAgLgEQgLgEAAgKQAAgHALgEIAGgDQAGgDADgKQACgKABgZIAAglIAAgjIgChnQgCgZgDgFQgDgDgNgEQgNgEAAgIQAAgGAFgEQAFgFAVgHIAXgGIAVgDQAHAAAEAFQADAEAAAKIAAAKIgCBbIAAALIABAGIADABIAFgFIAIgJQALgLANgGQANgGAOAAQAnAAAUAaQASAZABAzIAAAVIAAApIAAANQAAAMACAFQADAFAEADIAHADQAKAEABAHQAAAKgLAEQgLAEglAAQgdAAgLgEg");
	this.shape_8.setTransform(-90.5,0);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AgMCJQgLgDgIgIQgJgHgDgNQgDgNAAgiIAAh6IgVAAIgGgBIgDgGIAAgGQAAgHAYgVIAKgIIAIgIQAYgUAJAAIAGACQADACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgDACgFAAIgvAAIgDACIgCAGIAABwQAAAeAFAHQAFAIANAAQAIAAALgEIAPgEQAGAAADADQAEADgBAFQAAANgTALQgUAMgYAAQgNAAgMgEg");
	this.shape_9.setTransform(-111.7,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.theturkeyuse, new cjs.Rectangle(-122.1,-29.1,244.2,58.4), null);


(lib.thestuffinguse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgZAZQgJgKgBgPQABgOAJgKQALgLAOAAQAPAAAKALQALAKgBAOQABAPgLAKQgLALgOAAQgOAAgLgLg");
	this.shape.setTransform(120.3,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AhUCWQgdgTAAgZQAAgLAGgHQAGgIAMAAQAKAAAFAGQAGAFADAKQAFARAPAKQAOAKAcgBQAdAAAVgMQAUgLAAgRQAAgMgIgFQgHgHgOAAIgbADIgjACQgogBgWgOQgWgNAAgSQAAgMAIgLQAIgKAQgKQgNgMgHgOQgHgPAAgSQAAglAdgZQAcgZArAAIAXADIAjAHQAJAAAKgFQAKgFAOgJIAHAHIADAHQAAALgHAIQgIAKgNAGIAHATIACASQAAAmgbAYQgcAYgsAAIgZgCIgVgFIgHAIIgDAJQAAALALAFQALAFAXAAIAigDIAjgCQAgAAARANQARANAAAYQAAAkgkAZQgjAYg3AAQgrAAgdgRgAglhxQgMAOAAAYQAAAXALAOQAMAOATAAQASAAANgOQANgOAAgXQAAgYgNgOQgMgPgTAAQgSAAgMAPg");
	this.shape_1.setTransform(102.8,9.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AAeByQgLgEABgJQAAgIALgFIAIgDQAFgDADgKQACgKAAgZQAAhIgJgSQgJgTgZAAQgLAAgLAIQgMAHgFAMQgGAKgCASQgBARAAAtQAAAWABAIQACAHAGADIAIADQALAFAAAIQABAJgLAEQgMADgeAAQgjAAgLgDQgLgEAAgKQAAgIALgEIAGgCQAGgEACgHQACgIABgRIAAgQIgBgSIAAgXQAAgkgBgLQgCgLgFgCIgLgEQgOgFAAgHQABgGAEgDQAEgFAKgEIAhgKIAYgEQAGAAADADQADAEAAAHIAAAQIAAACIABAAIABAAIABAAIAGgFIAEgFQAZgXAcAAQARAAAQAHQAPAHAKANQALAMAEARQAEASABAlIAAAeIgBAPIAAANQAAAQACAHQADAGAFAEIAGACQALAEAAAIQABAKgLADQgKAEgkAAQggAAgLgDg");
	this.shape_2.setTransform(76.2,5.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AgoCkQgMgFAAgKQAAgHAMgEIAGgCQAFgEADgIQACgHAAgRIAAgQIAAgSIAAgZQAAgjgCgLQgCgLgEgBIgLgFQgNgEAAgHQgBgGAFgDQAEgFAKgEIAjgLIAWgFQAHABACAEQAEAEAAALIAAAOIgBAKIgCA5IAAACIgBA4QAAAWADAJQABAJAFADIAJADQAMAFAAAIQAAAJgMAEQgLADgeAAQghAAgMgDgAgchyQgKgJABgLQgBgOALgJQALgJAPAAQAOAAALAIQAJAJAAAMQAAANgKAJQgLAIgPABQgPgBgKgHg");
	this.shape_3.setTransform(56,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhACkQgLgEAAgJQAAgHALgEIAGgDQAGgDACgHQABgHAAgUIAAgWIAAhuIgZAAQgGAAgCgCQgCgCAAgHIAAgFQABgGACgCQACgDAFAAIAZAAIgCgSIgBgQQgBgjAWgTQAUgUAlAAQAaAAAQAMQAQAMABASQgBALgFAFQgGAGgLAAQgIAAgFgEQgGgDgEgGIgEgIQgJgRgNAAQgJAAgEAGQgGAGABAJIAFAZQAEAUABAQIAhAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgDACgFAAIghAAIAAB1QAAAeACAJQACAJAEACIAKADQAMAFAAAJQAAAJgLADQgLAEggAAQgiAAgLgEg");
	this.shape_4.setTransform(45,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("Ag/CkQgMgEAAgJQAAgHALgEIAGgDQAFgDACgHQACgHABgUIAAgWIAAhuIgaAAQgFAAgCgCQgCgCAAgHIAAgFQAAgGACgCQACgDAGAAIAXAAIgCgSIgBgQQABgjAUgTQAWgUAkAAQAaAAARAMQAPAMAAASQABALgGAFQgGAGgLAAQgIAAgFgEQgGgDgEgGIgEgIQgIgRgOAAQgJAAgEAGQgGAGAAAJIAGAZQAFAUAAAQIAhAAQAFAAADACQACACAAAHIAAAFQAAAGgDADQgCACgFAAIghAAIAAB1QAAAeACAJQABAJAGACIAJADQANAFgBAJQABAJgLADQgLAEghAAQghAAgLgEg");
	this.shape_5.setTransform(32,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AAxB0QgDgDAAgIIAAgQIAAgBIgBgBQgCAAgGAGIgDADQgLAMgOAFQgMAGgSAAQgRAAgPgHQgPgGgKgMQgLgNgFgTQgEgSAAgwIABgQIAAgRIAAgEQgBgTgCgFQgCgFgJgDIgJgDQgNgEAAgIQAAgGAEgDQAFgEAQgGIAfgIIAZgEQAFAAAEAFQACAFAAAKIAAAJIgCBVQgBAuAKASQAKASAXAAQAZAAAMgXQALgXAAg3IAAgSQAAgSgCgFQgDgGgHgCIgKgDQgNgEAAgIQABgFAEgEQAFgEAQgGIAegIIAYgEQAHAAACAFQADAEAAALIAAANIgDBdIAAAnIACAPQACAJAMAFIAEABQANAFAAAHQAAAFgEAEQgFAEgJAEIghALQgQAEgIAAQgGAAgEgEg");
	this.shape_6.setTransform(9.8,5.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AgLCJQgMgDgIgIQgJgHgDgNQgDgNAAgiIAAh6IgVAAIgGgBIgCgGIAAgGQgBgHAYgVIAKgIIAIgIQAZgUAIAAIAHACQACACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgCACgGAAIgvAAIgEACIgBAGIAABwQAAAeAFAHQAFAIANAAQAIAAALgEIAPgEQAGAAADADQAEADAAAFQgBANgTALQgUAMgYAAQgOAAgKgEg");
	this.shape_7.setTransform(-11.6,3.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("Ag4ClQgZgGgQgJQgKgFgGgUQgFgTgBgaQAAgLAFgFQADgGAIAAQAKAAAMAVIAFAKQAPAZARAMQARALAYAAQAZAAARgPQARgOAAgXQAAgghDgdIgIgDQg3gYgSgUQgTgUAAghQABgpAegaQAegbAwABIAbACIAgAHIAJgGIAIgCQAFAAAFADQAEAEAFAJQAIAOAEAOQAFAQAAALQgBAHgDAFQgEAEgGAAQgMAAgLgQIgEgFQgNgRgPgHQgPgJgUAAQgZAAgOAMQgPAMAAAVQABASAMANQALAMAxAVIAKAEQAoASATAPQAMALAHAQQAGAPABATQgBAuggAbQghAag5AAQgcgBgZgFg");
	this.shape_8.setTransform(-33.2,0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhKBWQggghgBgxQABg1AhgjQAigjAyAAQAtABAaAZQAZAZABArQAAAOgFAFQgEAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAHAAIAwAAIAMgCQACgBAAgGQABgWgPgPQgQgPgUAAQgbAAgOAYQgMAXAAAiQgBAjATAaQASAaAcAAQARAAAMgDQALgFAMgHIAIgGQALgKAGAAQAGAAADADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgVABQgwAAghgig");
	this.shape_9.setTransform(-71.1,5.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAgCkQgMgDAAgJQAAgJAMgEIAIgEQAGgDACgKQACgJAAgZQAAhJgJgSQgJgSgYAAQgMAAgLAHQgLAHgGAMQgFAKgCARQgCASAAAtQAAAXACAHQACAIAEACIAJAEQAMAEAAAJQAAAJgMADQgLAEgdAAQgkAAgLgEQgLgEAAgKQAAgHALgEIAGgDQAGgDADgKQACgKAAgZIAAglIAAgjIgBhnQgCgZgDgFQgDgDgNgEQgOgEAAgIQAAgGAGgEQAGgFAUgHIAXgGIAVgDQAHAAAEAFQADAEAAAKIgBAKIgCBbIAAALIACAGIADABIAFgFIAIgJQALgLAOgGQAMgGAOAAQAnAAATAaQAUAZgBAzIABAVIAAApIAAANQAAAMADAFQABAFAGADIAFADQALAEAAAHQABAKgLAEQgLAEglAAQgdAAgLgEg");
	this.shape_10.setTransform(-97.2,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgMCJQgLgDgIgIQgIgHgDgNQgEgNAAgiIAAh6IgVAAIgHgBIgBgGIAAgGQAAgHAYgVIAJgIIAJgIQAXgUAJAAIAGACQADACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgCACgGAAIgvAAIgEACIgBAGIAABwQAAAeAFAHQAFAIAOAAQAGAAAMgEIAQgEQAFAAADADQADADABAFQAAANgUALQgTAMgZAAQgNAAgMgEg");
	this.shape_11.setTransform(-118.4,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thestuffinguse, new cjs.Rectangle(-128.7,-29.1,257.5,58.4), null);


(lib.thesidesuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgYAZQgKgKAAgPQAAgOAKgKQAKgLAOAAQAPAAAKALQAKAKAAAOQAAAPgKAKQgKALgPAAQgOAAgKgLg");
	this.shape.setTransform(95.4,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgQB3IgZgEIgHAEIgHABIgFgBIgEgDQgHgGgIgTQgGgSAAgRQAAgIAEgEQAEgFAGAAQAKAAALASIAJAOQAGAJAMAFQANAFAMAAQAPAAAJgHQAJgIAAgMQAAgUgmgSIgNgHQgjgRgNgOQgNgPAAgWQAAgeAVgTQAVgTAhAAIAPABIAQADIALgEIAHgBQAMAAALASQAKASAAAUQAAAIgEAEQgDAFgHAAQgFAAgFgEQgFgFgHgLQgJgOgJgGQgJgFgNAAQgMAAgIAHQgJAIAAAMQABAKAIAIQAIAIAcAPIACABQBAAeAAAlQAAAggYAWQgZAVgkAAg");
	this.shape_1.setTransform(79.1,5.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AhKBWQghghABgxQgBg1AigjQAhgjA0AAQAsABAaAZQAaAZAAArQgBAOgEAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAIAAIAvAAIAMgCQADgBAAgGQgBgWgPgPQgPgPgUAAQgbAAgNAYQgNAXgBAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAGAAQAFAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgvAAghgig");
	this.shape_2.setTransform(57.3,5.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AhkCLQgbgfAAgyQAAg4AfgiQAfgjAxAAIAQACQAHACAEAFQADAFAAAGQAAAMgOAAIgGAAIgHgBQgZAAgPAVQgPAUAAAkQgBAmASAZQAQAYAZAAQAYAAANgNQAOgOAAgZIAAg/IAAhpQgBgQgCgGQgEgGgIgDIgGgCQgOgEgBgIQABgGAFgFQAFgEASgGIAZgIIAWgCQAIAAADAEQADAEAAALIAAALIgCCNIABBgQACAWAEACIAPAGQANACAAAIQAAALgiALIgXAGIgRACQgGAAgEgEQgCgDAAgIIAAgLIgBgEIgBgCIgHAFIgKAHQgNALgNAEQgNAFgOAAQgrAAgbgeg");
	this.shape_3.setTransform(32.4,0.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AgoCkQgMgFAAgKQAAgHAMgEIAGgCQAFgEADgIQACgHAAgRIAAgQIAAgSIAAgZQAAgjgCgLQgCgLgEgBIgLgFQgNgEAAgHQgBgGAFgDQAEgFAKgEIAjgLIAWgFQAHABACAEQAEAEAAALIAAAOIgBAKIgCA5IAAACIgBA4QAAAWADAJQABAJAFADIAJADQAMAFAAAIQAAAJgMAEQgLADgeAAQghAAgMgDgAgbhyQgLgJABgLQgBgOALgJQALgJAQAAQANAAALAIQAJAJAAAMQAAANgKAJQgLAIgPABQgPgBgJgHg");
	this.shape_4.setTransform(11.4,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("Ag4ClQgZgGgRgJQgIgFgGgUQgHgTAAgaQAAgLAEgFQAFgGAHAAQALAAALAVIAGAKQAOAZARAMQASALAXAAQAZAAARgPQARgOAAgXQAAgghDgdIgIgDQg3gYgSgUQgSgUAAghQAAgpAegaQAegbAwABIAbACIAgAHIAJgGIAHgCQAGAAAFADQAEAEAFAJQAIAOAFAOQADAQAAALQAAAHgDAFQgEAEgGAAQgMAAgMgQIgDgFQgNgRgPgHQgPgJgUAAQgZAAgOAMQgOAMAAAVQgBASAMANQAMAMAxAVIAKAEQApASASAPQANALAGAQQAHAPAAATQAAAughAbQggAag6AAQgcgBgZgFg");
	this.shape_5.setTransform(-8.3,0.3);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AhKBWQghghABgxQgBg1AigjQAhgjA0AAQAsABAaAZQAaAZAAArQgBAOgEAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAIAAIAvAAIAMgCQADgBAAgGQgBgWgPgPQgPgPgUAAQgbAAgNAYQgNAXgBAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAGAAQAFAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgvAAghgig");
	this.shape_6.setTransform(-46.2,5.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AAgCkQgLgDAAgJQAAgJALgEIAIgEQAGgDACgKQACgJAAgZQAAhJgJgSQgKgSgYAAQgLAAgLAHQgLAHgGAMQgFAKgCARQgCASAAAtQAAAXACAHQACAIAFACIAIAEQAMAEAAAJQAAAJgLADQgMAEgdAAQgkAAgLgEQgLgEAAgKQAAgHALgEIAGgDQAGgDADgKQADgKgBgZIAAglIAAgjIgBhnQgCgZgDgFQgCgDgOgEQgOgEAAgIQABgGAFgEQAGgFAUgHIAXgGIAVgDQAIAAADAFQADAEAAAKIgBAKIgBBbIAAALIABAGIADABIAFgFIAIgJQALgLANgGQAMgGAPAAQAnAAATAaQATAZAAAzIABAVIAAApIAAANQAAAMACAFQADAFAEADIAHADQALAEgBAHQAAAKgKAEQgLAEgkAAQgeAAgLgEg");
	this.shape_7.setTransform(-72.3,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgLCJQgMgDgIgIQgJgHgDgNQgDgNAAgiIAAh6IgVAAIgGgBIgCgGIAAgGQgBgHAYgVIAKgIIAIgIQAZgUAIAAIAHACQACACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgCACgGAAIgvAAIgEACIgBAGIAABwQAAAeAFAHQAFAIANAAQAIAAALgEIAPgEQAGAAADADQAEADAAAFQgBANgTALQgUAMgYAAQgOAAgKgEg");
	this.shape_8.setTransform(-93.5,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thesidesuse, new cjs.Rectangle(-103.8,-29.1,207.7,58.4), null);


(lib.thefeastuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgYAZQgLgKAAgPQAAgOALgKQAKgLAOAAQAPAAAKALQAKAKAAAOQAAAPgKAKQgLALgOAAQgOAAgKgLg");
	this.shape.setTransform(96.2,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgMCJQgLgDgIgIQgIgHgDgNQgEgNAAgiIAAh6IgVAAIgHgBIgCgGIAAgGQAAgHAZgVIAJgIIAJgIQAXgUAJAAIAGACQADACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgDACgFAAIgvAAIgEACIgBAGIAABwQAAAeAFAHQAFAIAOAAQAHAAALgEIAQgEQAFAAADADQADADAAAFQABANgUALQgTAMgZAAQgOAAgLgEg");
	this.shape_1.setTransform(81.9,3.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgQB3IgZgEIgHAEIgHABIgFgBIgEgDQgIgGgGgTQgHgSAAgRQAAgIAEgEQAEgFAGAAQALAAAKASIAJAOQAGAJAMAFQAMAFANAAQAPAAAJgHQAJgIAAgMQAAgUgmgSIgNgHQgjgRgNgOQgNgPAAgWQAAgeAVgTQAUgTAiAAIAPABIAQADIALgEIAIgBQALAAAKASQALASAAAUQAAAIgEAEQgDAFgHAAQgFAAgFgEQgFgFgHgLQgJgOgJgGQgJgFgNAAQgMAAgIAHQgJAIABAMQAAAKAIAIQAIAIAcAPIACABQBAAeAAAlQAAAggYAWQgZAVgkAAg");
	this.shape_2.setTransform(63.7,5.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AApBsIgMgMIgKAFQgcATgcAAQgiAAgVgUQgUgTAAggQAAgkAagUQAbgVAwAAQALAAAGAEQAFADAAAJQAAANgPAAQgWAAgOALQgOALAAATQAAASAMALQAMALAUAAQAVAAAKgKQAKgKAAgYIAAhWQAAgUgJgLQgJgLgPAAQgMAAgJAFQgKAFgJAKIgFAGQgOASgPAAQgJAAgFgGQgGgGAAgKQAAgVAbgPQAagPAqAAQAZAAASAHQASAHAKANQAHAIADAOQADAPAAAgIAABJQAAANACAGQACAHAFABIAHACQAOAEAAAIQAAALgPAJQgQAJgUAAQgKAAgLgMg");
	this.shape_3.setTransform(42,5.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhKBWQggghAAgxQAAg1AhgjQAigjAyAAQAtABAaAZQAZAZABArQAAAOgFAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAHAAIAwAAIAMgCQACgBAAgGQABgWgQgPQgOgPgVAAQgbAAgNAYQgOAXAAAiQAAAjASAaQATAaAcAAQARAAAMgDQAMgFAKgHIAJgGQALgKAGAAQAGAAADADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgVABQgxAAgggig");
	this.shape_4.setTransform(17.4,5.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("Ah0CjQgMgDAAgLQAAgJAMgEQAMgFACgEQAEgEACgiIABhZIgChUQgCgjgDgFQgCgCgMgGQgMgEAAgKQAAgJAKgEQALgDAnAAICMAAIAWgCIAMgDIAGACIAEAEQAFAIAEAQQAEAPAAAMQAAAKgDAFQgEAGgHAAQgIAAgKgQIgGgLQgFgGgLgEQgKgEgPAAIgfAAQgWAAgLADQgLACgEAFQgEAFgCAPIgCAsIAAASQAAALACADQACADAHAAIAkAAQATgBAHgFQAHgFACgOIABgFQADgXAMAAQAKAAAEAMQAEAMAAAsQAAAsgEAMQgDAMgLAAQgMAAgDgYIgBgEQgCgOgHgFQgHgGgTAAIgkAAQgGABgDADQgCAEAAAPIAAARIACBBQABANAFADIAKAFQAOAFAAAKQAAAKgNADQgNAFgjAAQglAAgNgFg");
	this.shape_5.setTransform(-8.2,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AhKBWQghghAAgxQAAg1AigjQAhgjA0AAQAsABAaAZQAaAZgBArQAAAOgDAFQgFAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAIAAIAvAAIALgCQADgBABgGQAAgWgPgPQgPgPgVAAQgbAAgOAYQgNAXABAiQAAAjASAaQASAaAcAAQARAAAMgDQAMgFALgHIAIgGQALgKAHAAQAEAAAEADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgWABQgwAAgggig");
	this.shape_6.setTransform(-47,5.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AAgCkQgMgDABgJQgBgJAMgEIAJgEQAFgDACgKQACgJAAgZQAAhJgJgSQgJgSgZAAQgLAAgLAHQgLAHgGAMQgFAKgCARQgCASAAAtQAAAXACAHQACAIAFACIAIAEQAMAEAAAJQAAAJgLADQgLAEgeAAQgkAAgLgEQgLgEAAgKQAAgHALgEIAGgDQAGgDADgKQACgKABgZIAAglIAAgjIgChnQgBgZgEgFQgDgDgNgEQgNgEAAgIQgBgGAGgEQAFgFAVgHIAXgGIAVgDQAHAAAEAFQADAEAAAKIAAAKIgDBbIAAALIACAGIADABIAFgFIAIgJQAMgLAMgGQANgGAOAAQAnAAAUAaQASAZABAzIAAAVIAAApIAAANQAAAMACAFQADAFAFADIAGADQAKAEABAHQAAAKgLAEQgLAEglAAQgdAAgLgEg");
	this.shape_7.setTransform(-73.1,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgMCJQgLgDgIgIQgJgHgCgNQgEgNAAgiIAAh6IgVAAIgHgBIgCgGIAAgGQAAgHAZgVIAJgIIAJgIQAXgUAJAAIAGACQADACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgDACgFAAIgvAAIgDACIgCAGIAABwQAAAeAFAHQAFAIANAAQAIAAALgEIAQgEQAFAAADADQAEADgBAFQAAANgTALQgUAMgYAAQgNAAgMgEg");
	this.shape_8.setTransform(-94.3,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thefeastuse, new cjs.Rectangle(-104.6,-29.1,209.3,58.4), null);


(lib.thedessertsuse = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006E47").s().p("AgYAZQgKgKAAgPQAAgOAKgKQAKgLAOAAQAPAAAKALQALAKAAAOQAAAPgLAKQgKALgPAAQgOAAgKgLg");
	this.shape.setTransform(128.4,13.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#006E47").s().p("AgRB3IgYgEIgGAEIgIABIgFgBIgEgDQgHgGgIgTQgGgSAAgRQAAgIAEgEQAEgFAGAAQAKAAALASIAJAOQAGAJAMAFQANAFAMAAQAPAAAJgHQAJgIAAgMQAAgUglgSIgOgHQgkgRgMgOQgNgPAAgWQABgeAUgTQAVgTAhAAIAPABIAQADIALgEIAHgBQAMAAALASQAKASAAAUQAAAIgEAEQgDAFgHAAQgFAAgFgEQgFgFgHgLQgJgOgJgGQgJgFgNAAQgMAAgJAHQgIAIAAAMQAAAKAJAIQAIAIAcAPIACABQBAAeAAAlQAAAggYAWQgZAVglAAg");
	this.shape_1.setTransform(112,5.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006E47").s().p("AgLCJQgMgDgIgIQgIgHgEgNQgDgNAAgiIAAh6IgVAAIgHgBIgBgGIAAgGQAAgHAXgVIAKgIIAIgIQAYgUAJAAIAHACQACACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgCACgGAAIgvAAIgEACIgBAGIAABwQAAAeAFAHQAFAIAOAAQAGAAAMgEIAPgEQAGAAADADQADADABAFQAAANgUALQgTAMgZAAQgNAAgLgEg");
	this.shape_2.setTransform(94.3,3.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#006E47").s().p("AhEByQgMgEAAgKQAAgIALgEIAGgCQAGgEACgHQADgIAAgRIAAgQIAAgSIAAgOQAAgpgCgNQgCgNgFgCIgLgEQgNgFAAgHQAAgGAEgEQAEgEAKgEIAfgKIAVgEQAKAAAEAfIABAFIABABQALgTANgJQANgKANAAQAQAAAKAKQAJAJAAAQQAAAQgHAJQgIAJgNAAIgLgCIgJgHIgGgJQgCgGgDAAQgQAAgGAWQgFAWAABFQAAAUACAKQACAKAHADIAJADQAOAEgBAJQABAJgNAEQgNADgfAAQgiAAgLgDg");
	this.shape_3.setTransform(77.9,5.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#006E47").s().p("AhKBWQghghAAgxQAAg1AigjQAhgjA0AAQAsABAaAZQAaAZgBArQAAAOgDAFQgFAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAIAAIAvAAIALgCQADgBABgGQAAgWgPgPQgPgPgVAAQgbAAgOAYQgNAXABAiQAAAjASAaQASAaAcAAQARAAAMgDQAMgFALgHIAIgGQALgKAHAAQAEAAAEADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgWABQgwAAgggig");
	this.shape_4.setTransform(56.5,5.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#006E47").s().p("AgQB3IgZgEIgHAEIgHABIgEgBIgFgDQgIgGgGgTQgHgSAAgRQAAgIAEgEQAEgFAGAAQALAAAKASIAJAOQAGAJAMAFQAMAFANAAQAPAAAJgHQAJgIAAgMQAAgUgmgSIgNgHQgjgRgNgOQgNgPAAgWQAAgeAVgTQAUgTAiAAIAPABIAQADIALgEIAHgBQAMAAAKASQALASAAAUQAAAIgEAEQgDAFgHAAQgFAAgFgEQgFgFgHgLQgJgOgJgGQgJgFgNAAQgMAAgIAHQgJAIABAMQAAAKAIAIQAIAIAcAPIACABQBAAeAAAlQAAAggYAWQgZAVgkAAg");
	this.shape_5.setTransform(34.4,5.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#006E47").s().p("AgRB3IgXgEIgHAEIgIABIgEgBIgFgDQgHgGgIgTQgGgSAAgRQAAgIAEgEQAEgFAGAAQALAAAKASIAJAOQAHAJAMAFQAMAFAMAAQAPAAAJgHQAJgIAAgMQAAgUglgSIgOgHQgkgRgMgOQgMgPAAgWQAAgeAUgTQAVgTAhAAIAPABIARADIALgEIAHgBQAKAAAMASQAKASAAAUQAAAIgDAEQgEAFgHAAQgFAAgFgEQgFgFgHgLQgJgOgJgGQgJgFgNAAQgMAAgJAHQgHAIgBAMQAAAKAJAIQAIAIAcAPIADABQA/AeAAAlQAAAggYAWQgZAVglAAg");
	this.shape_6.setTransform(14.7,5.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#006E47").s().p("AhKBWQggghgBgxQABg1AhgjQAhgjAzAAQAtABAaAZQAaAZgBArQAAAOgDAFQgFAEgRAAIhXAAQgIAAgEgEQgEgDAAgGQAAgHAEgDQAEgDAHAAIAwAAIALgCQADgBAAgGQAAgWgOgPQgPgPgVAAQgbAAgOAYQgMAXAAAiQgBAjATAaQASAaAcAAQARAAAMgDQAMgFALgHIAIgGQALgKAHAAQAFAAADADQADAEAAAFQAAAFgGAIQgFAIgKAHQgUARgTAIQgSAGgVABQgwAAghgig");
	this.shape_7.setTransform(-7.1,5.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#006E47").s().p("AgxClIgcgBIgUABIgTAAQgcAAgIgEQgJgDAAgKQAAgJAMgEQAMgFACgEQAEgEACgjIABhYIgChUQgCgjgDgFQgCgDgMgFQgMgFAAgJQAAgJAKgEQAJgEAcAAIATABIAYAAIAegBIAagBQBUAAAvAtQAuAsAABQQAABQgvApQgvAphbAAgAgxiBQgLADgCAHQgEAJgBAbIgCBFIACBXQACAkADAHQACAHAPAFQAPAFAVAAQA0AAAaggQAaggAAhAQAAhDgdgjQgfgkg4AAQgSAAgKAEg");
	this.shape_8.setTransform(-37.1,0.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#006E47").s().p("AhKBWQghghABgxQgBg1AigjQAhgjA0AAQAsABAaAZQAZAZAAArQAAAOgEAFQgEAEgRAAIhXAAQgIAAgDgEQgFgDAAgGQAAgHAFgDQADgDAIAAIAvAAIALgCQAEgBAAgGQgBgWgPgPQgPgPgUAAQgbAAgNAYQgNAXgBAiQABAjARAaQATAaAcAAQARAAAMgDQALgFALgHIAJgGQALgKAGAAQAFAAAEADQADAEAAAFQAAAFgFAIQgGAIgKAHQgUARgSAIQgTAGgWABQgvAAghgig");
	this.shape_9.setTransform(-79.2,5.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#006E47").s().p("AAgCkQgLgDAAgJQAAgJALgEIAIgEQAGgDACgKQACgJAAgZQAAhJgJgSQgKgSgYAAQgLAAgLAHQgLAHgGAMQgFAKgCARQgCASAAAtQAAAXACAHQACAIAFACIAIAEQAMAEAAAJQAAAJgLADQgMAEgdAAQgkAAgLgEQgLgEAAgKQAAgHALgEIAGgDQAGgDADgKQACgKAAgZIAAglIAAgjIgBhnQgCgZgDgFQgCgDgOgEQgOgEAAgIQABgGAFgEQAGgFAUgHIAXgGIAVgDQAHAAAEAFQADAEAAAKIAAAKIgCBbIAAALIABAGIADABIAFgFIAIgJQALgLANgGQAMgGAPAAQAnAAAUAaQASAZAAAzIABAVIAAApIAAANQAAAMACAFQACAFAFADIAHADQALAEgBAHQAAAKgKAEQgLAEgkAAQgeAAgLgEg");
	this.shape_10.setTransform(-105.3,0);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#006E47").s().p("AgLCJQgMgDgIgIQgJgHgDgNQgDgNAAgiIAAh6IgVAAIgGgBIgDgGIAAgGQAAgHAYgVIAKgIIAIgIQAZgUAIAAIAHACQACACAAADIAAArIAzAAQAGAAACACQACACAAAHIAAAFQAAAGgCADQgDACgFAAIgvAAIgDACIgCAGIAABwQAAAeAFAHQAFAIANAAQAIAAALgEIAPgEQAGAAADADQADADAAAFQAAANgTALQgUAMgYAAQgOAAgKgEg");
	this.shape_11.setTransform(-126.5,3.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.thedessertsuse, new cjs.Rectangle(-136.8,-29.1,273.6,58.4), null);


(lib.ordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAXAwIgXhMIAAAAIgWBMIgOAAIgchfIAOAAIAVBLIAXhLIANAAIAXBLIAAAAIAVhLIAOAAIgcBfg");
	this.shape.setTransform(35.7,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_1.setTransform(23.3,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAXAwIgxhNIAABNIgOAAIAAhfIASAAIAxBMIAAhMIANAAIAABfg");
	this.shape_2.setTransform(12.4,0.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_3.setTransform(0.1,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgfAwIAAhfIA9AAIAAAMIgvAAIAAAdIAsAAIAAAKIgsAAIAAAgIAxAAIAAAMg");
	this.shape_4.setTransform(-8.2,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgpAwIAAhfIAhAAQAIAAAJADQAJADAIAFQAHAGAFAJIADAKIABALIgBALIgDAKIgGAIIgGAHQgIAGgJADQgLADgGAAgAgcAkIARAAQAJAAAGgCQAHgDAGgEQAFgFADgHIACgHIABgIIgBgHIgCgIQgDgGgFgFQgGgEgHgDQgGgCgJAAIgRAAg");
	this.shape_5.setTransform(-17.4,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AASAwIgXgrIgPAAIAAArIgNAAIAAhfIAfAAIAMACQAGABAEADQAFADADAFQADAFAAAIQAAAKgHAHIgHAEIgKADIAbAsgAgUgFIAQAAIAHgBIAHgCQAEgCABgDQACgDAAgEQAAgFgCgDIgEgEIgHgDIgHAAIgRAAg");
	this.shape_6.setTransform(-26.5,0.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgKAxIgJgDQgJgDgHgHQgHgHgEgJQgEgJAAgLQAAgKAEgKQAEgJAHgGQAHgHAJgEIAJgCIAKgBQALAAAJADIAJAFIAHAGQAHAGAEAJQAEAKAAAKQAAALgEAJQgEAJgHAHIgHAGIgJAEQgJAEgLAAIgKgBgAgOgjQgHAEgEAFQgFAFgDAHQgCAHAAAHQAAAIACAHQADAHAFAFQAFAFAGADQAHADAHAAQAIAAAHgDQAHgDAEgFQAFgFADgHQACgHAAgIQAAgHgCgHQgDgHgFgFQgEgFgHgEQgHgDgIAAQgHAAgHADg");
	this.shape_7.setTransform(-36.8,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ordernow, new cjs.Rectangle(-44.5,-10.3,89,20.6), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.logokale = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgeAfQgNgNAAgSQAAgRANgNQANgNARAAQASAAANANQANANAAARQAAASgNANQgNANgSAAQgRAAgNgNgAgYgYQgKAKAAAOQAAAQAKAKQAKAKAOAAQAPAAAKgKQAKgKAAgQQAAgOgKgKQgKgKgPAAQgOAAgKAKgAAMAZIgOgVIgFAAIAAAVIgJAAIAAgzIATAAQARAAAAAPQAAANgNABIAPAWgAgHgDIAGAAQANAAAAgIQAAgHgMAAIgHAAg");
	this.shape.setTransform(130.4,59.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AjnEaQgVgDgGgEQgKgFAAgNQAAgKAFgHQAHgHAIAAIARAAQAKAAAFgLQACgKABgXIAAl5QgBgXgCgKQgFgLgKAAIgRAAQgIAAgHgHQgFgHAAgKQAAgNAKgFQAGgEAVgDQBdgNBrAAQBOAAA2ASQA0ASAnAoQAlAlAUA5QAUA4AABEQAABNgZA9QgaA+guAlQglAegxAOQgwAOhFAAQhrAAhdgNgAgwjrQgcAFgJALQgKAMAAAhIAAFjQAAAhAUALQAOAHAnADQBMAEAthAQAqg/AAhwQAAhwgqg/Qgrg/hKAAIgeADg");
	this.shape_1.setTransform(62.2,30.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNBlQgFgDAAgHIAAiTQAAgKgMAAIgyAAQgKAAAAgPIABgNQACgIAHAAICfAAQAMAAAAASQAAASgLAAIgyAAQgMAAAAAKIABCTQAAAHgFADQgEACgKAAQgJAAgEgCg");
	this.shape_2.setTransform(81.2,88.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhMBmQgNAAAAgPIAAiuQAAgOANAAICbAAQAGAAADAFQACADAAAJQAAAKgCADQgDAGgHAAIh5AAQgIAAAAAJIAAAbQAAAKAKAAIBFAAQALAAAAASQAAAQgKAAIhFAAQgLAAAAALIAAAeQAAAKAKAAIB4AAQAKAAAAATQAAARgKAAg");
	this.shape_3.setTransform(52.4,88.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAxBgIhAhGQgLgJgTAAQgFAAgEAEQgDAFAAAGIAAA8QAAAMgVAAQgRAAAAgNIAAi0QAAgIAFgCQAEgCALAAQASAAAAAMIAAA3QAAANAJAAQALAAAFgDQAEgBAFgFIBJhDQANgLAMAMQAMALgKAKIhAA6QgJAIAJAJIBOBWQAIAIgGAFQgFAFgNAAQgTAAgHgIg");
	this.shape_4.setTransform(22.6,88.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAuBeIgfgyQgGgJgKAAIgtAAQgDAAgEADQgEAEABADIAAAyQAAAGgKACIgPAAQgMAAAAgMIAAi5QgBgIAKAAIBqAAQAgAAAUATQAVATAAAfQAAAYgPAPQgIAJgPAKQgHAGADAGIAjAyQAFAIgFADQgEAFgPAAQgQAAgHgJgAg4g4IAAAuQAAAFAEADQAEACAFAAIA+AAQAQAAALgIQALgIAAgRQAAgQgLgJQgLgJgQABIg+AAQgNAAAAAKg");
	this.shape_5.setTransform(-11.1,88.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("ABCBgIgOgbQgCgHgHAAIhTAAQgJAAgEALIgMAXQgDAHgSAAQgWAAAFgMIBZi4QAFgKAKAAQALAAAFAJIBXC6QADAGgJAEQgGACgIAAQgPAAgDgIgAgEgdIgYAyQgDAIAIAAIAwAAQABAAABAAQAAAAABgBQABAAAAAAQAAgBABAAQACgCgCgDIgZgzQgBgDgEAAQgCAAgCADg");
	this.shape_6.setTransform(-44.3,88.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("ABZBkQgFgDAAgEIgOhsQgCgGgFAAQgDAAgDADIgxA+QgEAGgFAAQgHAAgEgHIgtg7QgCgDgEAAQgFAAgBAHIgOBoQgCALgTAAQgGAAgFgDQgGgDAAgFIAViwQACgJADgEQAEgEALAAQAKAAAFAJIA4BPQAFAHAEAAQAEAAAHgIIA7hQQAEgIALAAQAGAAADACQAEADACAIIAVC1QABALgXAAQgFAAgFgDg");
	this.shape_7.setTransform(-78.1,88.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AipF/QhPhTAAiLQAAhZAghEQAghCA6gnQAZgTAmgTQAmgTAngOQAKgDgDgJQgCgKgNADQg7ALgrgSQgWgJgdgRQghgUgJgEQgvgWg6AZQgVAJgMgLQgLgLAGgXQAXhWBDg3QBKg9BQAXQA0APAlA0QAmA2AfALQATAGgBAPQAAAOgRADQgaAFgjgRQgggPgdgbQgfgcgvgCQgsgCgbAVQgLAIADAHQAEAHAKgDQAggHAdAGQAoAIAbAgQAkAoAuAPQA4ASAugfIAZgWQANgNAMAEQAPAEgBAUQgBAUgTAZQgiAsg+AeQhFAjgeAdQgwAwgTA9QgPAzAABQQAAByAqBAQAqBABKAAQBKAAArhCQAqhBAAhwQAAhfgXg4QgZg6g2gVQgbgKAFgTQAFgUAhgEQA3gGA8AsQBoBOAACjQAACOhPBVQhQBUiHAAQiDAAhPhUg");
	this.shape_8.setTransform(14.6,-54.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("ABnDwQhFg1gYheIgBgCQgCgMgHAAQgGAAgCALIgBACQgYBfhGA1QhIA3hoAAQh+AAhMhQQhMhQAAiFQAAiHBMhRQBLhQCAAAQBpAABHA3QBHA2AXBgQACALAGAAQAHgBACgKIABgBQAXhgBGg1QBHg3BoAAQB/AABNBQQBMBPAACFQAACHhMBRQhNBRiBAAQhmAAhHg3gACniqQgpA/AABuQAABrApA/QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/gAmFiqQgoA/AABuQAABsAoA+QAoA9BIAAQBGAAApg/QApg/AAhrQAAhsgqg+QgphAhHAAQhGAAgoA/g");
	this.shape_9.setTransform(-21,30.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ai5EbQgWAAgJgFQgIgFAAgOQAAgKAGgHQAHgHAJAAIARAAQAKAAAEgLQADgJAAgYIAAl7QAAgXgDgKQgCgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgJQAAgOAJgGQAIgFAWAAIFvAAQAaAAAEAVIAMA7QAEAQgFAJQgFAJgMAAQgPAAgHgOQgEgFgFgNQgFgQgPgFQgNgEggAAIhtAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAFADAdAAIBFAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAJgOAAQgTAAgEgXIAAgFQgCgNgIgDQgHgEgbAAIhFAAQgeAAgEAEQgIAFAAAZIAACLQAAAbACAGQAGALAMAAIATAAQAKAAAGAHQAGAHAAAKQAAAOgJAFQgIAFgYAAg");
	this.shape_10.setTransform(-98.4,30.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AhTEbIgTgEQgIAAgKAJQgKAIgJAAQgLAAgGgHQgGgGgEgQIgVhUQgCgIAAgJQAAgMAHgIQAIgHAMAAQAMAAAJALIAMARQAWAfAhASQAiASAkAAQApAAAagVQAZgUAAgiQAAghgbgfQgbgdg/gsIhNg2QgSgPgTgWQgggmAAgzQAAg9ArgmQArgmBGAAQAlAAAjAIIAWAFIALACQAJAAALgIIAJgFQAEgCAFAAQASAAAGAYIAUBcQABAEAAAIQAAAIgHAGQgHAGgKAAQgMAAgLgOQgNgVgHgIQgGgGgOgLQgjgbgtAAQgcAAgSAPQgRAQAAAaQAAAXAJALQAMASAbAWIApAdQAzAkAWARQAXASAUAUQAWAWAMAfQAMAeAAAhQAABJgyAtQgzAthUAAQgzAAglgNg");
	this.shape_11.setTransform(110.1,30.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Ah+EYQgLgJgHgYIhJjYQgBgFgEAAQgFAAgBAFIhNDYQgKAagHAHQgNAJgQAAQgTAAgKgJQgLgJgJgYIimm+QgKgagHgHQgHgHgUgFQgOgCgFgFQgFgFAAgLQAAgVAdgBICvAAQAcAAAAAYQAAAKgHAFQgHAFgRABQgOACgGAFQgGAFAAAJQAAAJADAKIBzFHQACAGAFgBQAEAAACgGIA/i2QAIgYgHgYIglhuQgEgJgHgFQgGgEgPgEQgNgDgGgGQgFgEAAgKQAAgaAdAAICnAAQAdAAAAAYQAAASgcAEQgRACgFAFQgGAFAAAMQAAAKAIAZIBfEsQACAFAEAAQAFAAABgGIBdk6QAEgLAAgJQAAgSgdgEQgbgCAAgVQAAgNAHgGQAIgFARgBIElAAQAVABAIAFQAIAFAAAOQAAAKgGAIQgGAGgJAAIgQAAQgLAAgFALQgCAIAAAZIAABtQAAAeAFAGQAGAHAXAAIB0AAQAXAAAHgIQADgDAAgHIABgdIAAhpQAAgbgDgGQgFgLgKAAIgQAAQgKAAgHgGQgGgIAAgKQAAgOAIgFQAJgFAWgBICaAAQAWABAJAFQAJAFAAAOQAAAKgHAIQgGAGgJAAIgSAAQgEAAgEADQgFADgBAFQgDAJAAAYIAAF9QAAAXADAKQABAFAFACQAEADAEABIASAAQAJAAAGAGQAHAIAAAJQAAAOgJAFQgIAGgXAAIiaAAQgWAAgIgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIAQAAQAKAAAFgLQADgGAAgbIAAh8IgBgeQAAgHgDgEQgHgHgXAAIh0AAQgXAAgGAGQgFAHAAAdIAACCQAAAYACAJQAFALALAAIAQAAQAJAAAGAGQAGAIAAAKQAAAOgIAEQgIAGgVAAIiaAAQgWAAgJgGQgIgFAAgOQAAgJAGgIQAHgGAJAAIARAAQAEgBAFgDQAEgCABgFQADgGAAgbIAAl9QAAgwgkAEQgLABgHAKQgIAIgGAWIiHGzQgJAfgKALQgLALgTAAQgTAAgLgJg");
	this.shape_12.setTransform(-74.6,-36.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AihEbQgWAAgIgFQgIgFAAgOQAAgKAGgHQAGgGAJAAIARAAQAEAAAEgDQAEgEACgEQADgIAAgXIAAl/QAAgZgDgJQgDgLgLABIgRAAQgKgBgGgGQgHgHAAgLQAAgNAJgGQAJgFAWAAICcAAQAWAAAJAFQAJAGAAANQAAALgGAHQgHAGgJABIgSAAQgOgBgDALQgDAGAAAcIAAFjQAAAdACAJQACAJAIAFQAGAEALACQALACAagBIAwAAQAvAAAPgfIAIgPQAIgQAPgBQAMAAAFAJQAFAJgEAQIgNBCQgEAVgaAAg");
	this.shape_13.setTransform(69.2,-37.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AjREWQgIgGAAgOQAAgJAGgHQAGgGAJAAIARAAQAEAAAEgEQAEgDABgEQAEgIAAgaIAAl7QAAgZgEgIQgBgGgEgDQgEgEgEAAIgRAAQgJAAgHgHQgGgHAAgKQAAgNAJgGQAIgFAWAAIFSAAQAZAAAFAVIAMA7QADAQgFAJQgFAIgMAAQgPAAgGgNQgDgCgGgQQgGgQgPgFQgMgEggAAIhQAAQghAAgJAJQgIAJAAAiIAABkQAAAaAIAFQAEADAeAAIAmAAQAbAAAIgDQAHgDACgNIAAgFQAEgWATAAQAOAAAFAJQAFAJAAAWIAABHQAAAWgFAJQgFAIgOAAQgTAAgEgWIAAgFQgCgNgIgDQgHgEgbAAIgmAAQgeAAgEAEQgIAFAAAZIAABsQAAAiADALQADALAKAEQAPAFAiAAIBVAAQAvAAAPgfIAHgQQAIgQAPAAQAMAAAFAJQAFAJgDAQIgNBCQgDALgHAFQgHAFgOAAIlhAAQgWAAgIgFg");
	this.shape_14.setTransform(114.4,-37.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#0C6E47").s().p("AqoZNQk7iFjyjyQjyjziFk6QiJlFAAljQAAlkCJlFQCFk6DyjzQDzjyE6iFQFFiJFjAAQFkAAFFCJQE6CFDyDyQDyDzCGE6QCJFFAAFkQAAFjiJFFQiGE6jyDzQjyDyk6CFQlFCJlkAAQljAAlFiJg");

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-175,-175,350,350);


(lib.holidaymainstable = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpagebannerholidaymainstable();
	this.instance.parent = this;
	this.instance.setTransform(-150,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainstable, new cjs.Rectangle(-150,-300,300,600), null);


(lib.holidaymainsstuffing = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpageholidaymainsstuffing();
	this.instance.parent = this;
	this.instance.setTransform(-55,-55);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsstuffing, new cjs.Rectangle(-55,-55,110,110), null);


(lib.holidaymainspotatoes = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.halfpageholidaymainspotatoes();
	this.instance.parent = this;
	this.instance.setTransform(-79.5,-109.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainspotatoes, new cjs.Rectangle(-79.5,-109.5,159,219), null);


(lib.holidaymainscranberries_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.holidaymainscranberries();
	this.instance.parent = this;
	this.instance.setTransform(-83.5,-54);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscranberries_1, new cjs.Rectangle(-83.5,-54,167,108), null);


(lib.holidaymainscinnamonbuns_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.holidaymainscinnamonbuns();
	this.instance.parent = this;
	this.instance.setTransform(-78,-71);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainscinnamonbuns_1, new cjs.Rectangle(-78,-71,156,142), null);


(lib.holidaymainsbrusselsprouts_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.holidaymainsbrusselsprouts();
	this.instance.parent = this;
	this.instance.setTransform(-56,-101.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsbrusselsprouts_1, new cjs.Rectangle(-56,-101.5,112,203), null);


(lib.holidaymainsapples = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.holidaymainsapple();
	this.instance.parent = this;
	this.instance.setTransform(-53.5,-52.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainsapples, new cjs.Rectangle(-53.5,-52.5,107,105), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgVZgtdMAqzAAAMAAABa8MgqzAAAg");
	this.shape.setTransform(0,0,1.091,1.029);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-150.5,-300.5,301,601), null);


(lib.ctarollovervideo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("ApcBzIAAjlIS5AAIAADlg");
	this.shape.setTransform(0,0,1.116,1.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarollovervideo, new cjs.Rectangle(-67.5,-17.2,135.1,34.5), null);


(lib.ctarectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AqiCtIAAlZIVFAAIAAFZg");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.ctarectangle, new cjs.Rectangle(-67.5,-17.2,135.1,34.6), null);


(lib.blackwideskyscraper = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("EgRBA2FMAAAhsJMAiDAAAMAAABsJg");
	this.shape.setTransform(0,0,0.753,0.867);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.blackwideskyscraper, new cjs.Rectangle(-82.1,-300,164.3,600.1), null);


(lib.thefeast = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.thesidesuse();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.thefeast, new cjs.Rectangle(-103.8,-29.1,207.7,58.4), null);


(lib.ctarolloverorange = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// Layer 1
	this.instance = new lib.ctarollovervideo();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-67.5,-17.2,135.1,34.5);


// stage content:
(lib.halfpagebannerholidaymains = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_58 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_251 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(58).call(this.frame_58).wait(193).call(this.frame_251).wait(4));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(150.3,301.6,1.456,0.919,0,0,0,0.2,0.1);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(255));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(255));

	// fade-from-white
	this.instance_1 = new lib.blackwideskyscraper();
	this.instance_1.parent = this;
	this.instance_1.setTransform(150.2,300,1.826,1,0,0,0,0.1,0);
	this.instance_1.filters = [new cjs.ColorFilter(0, 0, 0, 1, 255, 255, 255, 0)];
	this.instance_1.cache(-84,-302,168,604);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(246));

	// logo
	this.instance_2 = new lib.logokale("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,37.1,0.003,0.003,0,0,0,0,17.5);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({x:150},0).to({scaleX:0.29,scaleY:0.29,y:42.1,alpha:1},6,cjs.Ease.get(1)).to({regX:0.2,regY:17.7,scaleX:0.27,scaleY:0.27,x:150.1,y:41.7},7,cjs.Ease.get(1)).wait(233));

	// the-sides
	this.instance_3 = new lib.thesidesuse();
	this.instance_3.parent = this;
	this.instance_3.setTransform(150,226.2);
	this.instance_3.alpha = 0;

	this.instance_4 = new lib.thefeast();
	this.instance_4.parent = this;
	this.instance_4.setTransform(150,226.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).to({state:[{t:this.instance_3}]},124).to({state:[{t:this.instance_3}]},10).to({state:[{t:this.instance_3}]},30).to({state:[{t:this.instance_4}]},5).wait(86));
	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(124).to({alpha:1},10).wait(30).to({_off:true},5).wait(86));

	// the-feast
	this.instance_5 = new lib.thefeastuse();
	this.instance_5.parent = this;
	this.instance_5.setTransform(150,226.2);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(204).to({alpha:1},10).wait(41));

	// the-desserts
	this.instance_6 = new lib.thedessertsuse();
	this.instance_6.parent = this;
	this.instance_6.setTransform(150,226.2);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(164).to({alpha:1},10).wait(30).to({alpha:0},5).wait(46));

	// well-make-the-turkey
	this.instance_7 = new lib.wellmakeuse();
	this.instance_7.parent = this;
	this.instance_7.setTransform(150,173.8);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(45).to({alpha:1},10).wait(200));

	// the-stuffing
	this.instance_8 = new lib.thestuffinguse();
	this.instance_8.parent = this;
	this.instance_8.setTransform(150,226.2);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(84).to({alpha:1},10).wait(30).to({alpha:0},5).wait(126));

	// the-turkey
	this.instance_9 = new lib.theturkeyuse();
	this.instance_9.parent = this;
	this.instance_9.setTransform(150,226.2);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(45).to({alpha:1},10).wait(29).to({alpha:0},5).wait(166));

	// you-take-the-credit
	this.instance_10 = new lib.youtakethecredit();
	this.instance_10.parent = this;
	this.instance_10.setTransform(150,279.5);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(239).to({alpha:1},10).wait(6));

	// order-now
	this.instance_11 = new lib.ordernow();
	this.instance_11.parent = this;
	this.instance_11.setTransform(150,342.9);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(58).to({alpha:1},10).wait(187));

	// cta-rollover
	this.cta_rollover = new lib.ctarolloverorange();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(150.1,343);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(58).to({alpha:1},10).wait(187));

	// cta-rectangle
	this.instance_12 = new lib.ctarectangle();
	this.instance_12.parent = this;
	this.instance_12.setTransform(150,342.8);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(58).to({alpha:1},10).wait(187));

	// stuffing
	this.instance_13 = new lib.holidaymainsstuffing();
	this.instance_13.parent = this;
	this.instance_13.setTransform(55,55);
	this.instance_13.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(15).to({alpha:1},10).wait(230));

	// cinnamon-buns
	this.instance_14 = new lib.holidaymainscinnamonbuns_1();
	this.instance_14.parent = this;
	this.instance_14.setTransform(222,71);
	this.instance_14.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(20).to({alpha:1},10).wait(225));

	// brussel-sprouts
	this.instance_15 = new lib.holidaymainsbrusselsprouts_1();
	this.instance_15.parent = this;
	this.instance_15.setTransform(56,453.5);
	this.instance_15.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(25).to({alpha:1},10).wait(220));

	// cranberries
	this.instance_16 = new lib.holidaymainscranberries_1();
	this.instance_16.parent = this;
	this.instance_16.setTransform(128.5,546);
	this.instance_16.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(30).to({alpha:1},10).wait(215));

	// apples
	this.instance_17 = new lib.holidaymainsapples();
	this.instance_17.parent = this;
	this.instance_17.setTransform(246.5,547.5);
	this.instance_17.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(35).to({alpha:1},10).wait(210));

	// potatoes
	this.instance_18 = new lib.holidaymainspotatoes();
	this.instance_18.parent = this;
	this.instance_18.setTransform(220.5,417.5);
	this.instance_18.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(40).to({alpha:1},10).wait(205));

	// table
	this.instance_19 = new lib.holidaymainstable();
	this.instance_19.parent = this;
	this.instance_19.setTransform(150,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(255));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(150,300,300,603);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 300,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	webfonts: {},
	manifest: [
		{src:"images/index_atlas_.png", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;